name: Build and Output Hello

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Install build essentials
    - name: Install build essentials
      run: sudo apt-get update && sudo apt-get install build-essential -y

    # Step 3: Compile hello.c
    - name: Compile hello.c
      run: gcc hello.c -o hello

    # Step 4: Run the compiled executable (optional)
    - name: Run the executable
      run: ./hello

    # Step 5: Upload the executable as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-executable
        path: ./hello
